# ==================================================================================
# Archivo de Configuracion para vitalsd (Micro-Daemon)
# Ubicacion final: /etc/vitalsd/vitalsd.conf
# ==================================================================================

INTERVALO_REVISION=5
UMBRAL_CPU=2
UMBRAL_RAM=7
